'use client';
import {useCallback,useEffect,useState} from 'react';
import type {User} from '@supabase/supabase-js';
import {editProposal,makeExtractiveDraft,parseTranscript,validateIntake} from './domain';
import {EMPTY_WORKSPACE,SAMPLE_WORKSPACE} from './demo';
import {ensureOrganization,loadCloudWorkspace,unwrap} from './cloud-workspace';
import {getSupabaseBrowser,uploadPrivateAsset} from './supabase-browser';
import {customerFromRow,documentFromRow,meetingFromRow,proposalFromRow} from './supabase-mappers';
import type {ConnectionStatus,Customer,Intake,Minutes,Proposal,ReferenceDocument,WorkspaceData} from './types';

const STORAGE_KEY='meeting-workspace-demo-v1';
const uid=(prefix:string)=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const uuid=()=>crypto.randomUUID();

export function useWorkspace(){
 const client=getSupabaseBrowser();
 const [data,setData]=useState<WorkspaceData>(EMPTY_WORKSPACE);const [hydrated,setHydrated]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
 const [user,setUser]=useState<User|null>(null);const [organizationId,setOrganizationId]=useState<string|null>(null);const [mode,setMode]=useState<'demo'|'cloud'>('demo');const [authNotice,setAuthNotice]=useState<string|null>(null);
 const [connection,setConnection]=useState<ConnectionStatus>({supabase:false,supabaseConfigured:false,supabaseReachable:false,openai:false,mode:'demo'});
 const restoreLocal=useCallback(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);const stored:WorkspaceData=raw?JSON.parse(raw):SAMPLE_WORKSPACE;setData({...stored,meetings:stored.meetings.map(({audioUrl:_discarded,...meeting})=>meeting)});}catch{setData(SAMPLE_WORKSPACE);}},[]);
 useEffect(()=>{restoreLocal();setHydrated(true);},[restoreLocal]);
 useEffect(()=>{if(hydrated&&mode==='demo')localStorage.setItem(STORAGE_KEY,JSON.stringify(data));},[data,hydrated,mode]);
 useEffect(()=>{fetch('/api/status',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(setConnection).catch(()=>setConnection({supabase:false,supabaseConfigured:false,supabaseReachable:false,openai:false,mode:'demo'}));},[]);
 const openCloud=useCallback(async(nextUser:User)=>{if(!client)return;setBusy(true);setError(null);try{setUser(nextUser);const org=await ensureOrganization(client,nextUser.email??'내');setOrganizationId(org);setMode('cloud');setData(await loadCloudWorkspace(client));}catch(e){setError(e instanceof Error?e.message:'클라우드 데이터를 불러오지 못했습니다.');}finally{setBusy(false);setHydrated(true);}},[client]);
 useEffect(()=>{if(!client)return;const {data:{subscription}}=client.auth.onAuthStateChange((event,session)=>{if((event==='SIGNED_IN'||event==='INITIAL_SESSION')&&session?.user)setTimeout(()=>void openCloud(session.user),0);if(event==='SIGNED_OUT'){setUser(null);setOrganizationId(null);setMode('demo');restoreLocal();}});return()=>subscription.unsubscribe();},[client,openCloud,restoreLocal]);
 const run=async<T,>(work:()=>Promise<T>|T)=>{setBusy(true);setError(null);try{return await work();}catch(e){const message=e instanceof Error?e.message:'처리 중 오류가 발생했습니다.';setError(message);throw e;}finally{setBusy(false);}};
 const requireCloud=()=>{if(!client||!organizationId||!user)throw new Error('Supabase 로그인이 필요합니다.');return{client,organizationId,user};};
 const refreshCloud=async()=>{if(client&&mode==='cloud')setData(await loadCloudWorkspace(client));};
 return {data,hydrated,busy,error,connection:{...connection,mode},user,organizationId,mode,authNotice,clearError:()=>setError(null),
  signIn:(email:string)=>run(async()=>{if(!client)throw new Error('Supabase 환경 변수가 없습니다.');const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});if(error)throw error;setAuthNotice('로그인 링크를 이메일로 보냈습니다. 같은 브라우저에서 링크를 열어 주세요.');}),
  signOut:()=>run(async()=>{if(client){const {error}=await client.auth.signOut();if(error)throw error;}}),
  addCustomer:(input:Omit<Customer,'id'|'createdAt'>)=>run(async()=>{if(mode==='cloud'){const c=requireCloud();const row=unwrap(await c.client.from('customers').insert({organization_id:c.organizationId,...input}).select('*').single());setData(d=>({...d,customers:[customerFromRow(row),...d.customers]}));return;}setData(d=>({...d,customers:[{...input,id:uid('cus'),createdAt:new Date().toISOString()},...d.customers]}));}),
  createMeeting:(input:Intake)=>run(async()=>{const validation=validateIntake({audio:input.audio,text:input.text});if(validation.length)throw new Error(validation.join(' '));if(!input.text)throw new Error('클로바노트 TXT가 필요합니다.');const textFile=input.text;if(textFile.name.toLowerCase().endsWith('.docx'))throw new Error('TXT 기록을 사용해 주세요.');const transcript=await textFile.text();const segments=parseTranscript(transcript);
   if(mode==='cloud'){const c=requireCloud(),id=uuid();const row=unwrap(await c.client.from('meetings').insert({id,organization_id:c.organizationId,customer_id:input.customerId,title:input.title,held_at:new Date(input.heldAt).toISOString(),participants:input.participants,transcript,segments,audio_name:input.audio?.name??null,text_name:textFile.name,status:'draft'}).select('*').single());setData(d=>({...d,meetings:[meetingFromRow(row),...d.meetings]}));for(const [kind,file] of [['transcript',textFile],['audio',input.audio]] as const){if(!file)continue;const assetId=uuid(),path=`${c.organizationId}/${id}/${assetId}/${file.name}`;unwrap(await c.client.from('assets').insert({id:assetId,organization_id:c.organizationId,meeting_id:id,owner_id:c.user.id,kind,object_path:path,name:file.name,size:file.size,status:'pending'}).select('id').single());await uploadPrivateAsset(file,path);const ready=await c.client.rpc('mark_asset_ready',{p_asset_id:assetId});if(ready.error)throw ready.error;}return id;}
   const id=uid('mtg');setData(d=>({...d,meetings:[{id,customerId:input.customerId,title:input.title,heldAt:input.heldAt,participants:input.participants,status:'draft',transcript,segments,minutes:null,audioName:input.audio?.name??null,textName:textFile.name,audioUrl:input.audio?URL.createObjectURL(input.audio):undefined,version:1,createdAt:new Date().toISOString()},...d.meetings]}));return id;}),
  analyze:(id:string)=>run(async()=>{const meeting=data.meetings.find(m=>m.id===id);if(!meeting)throw new Error('미팅을 찾을 수 없습니다.');if(mode==='cloud'){const c=requireCloud();if(connection.openai){const {data:{session}}=await c.client.auth.getSession();const response=await fetch(`/api/meetings/${id}/analyze`,{method:'POST',headers:{Authorization:`Bearer ${session?.access_token}`}});if(!response.ok)throw new Error((await response.json()).error??'분석하지 못했습니다.');await refreshCloud();return;}const minutes=makeExtractiveDraft(meeting.segments);const row=unwrap(await c.client.from('meetings').update({minutes,status:'review'}).eq('id',id).select('*').single());setData(d=>({...d,meetings:d.meetings.map(m=>m.id===id?meetingFromRow(row):m)}));return;}setData(d=>({...d,meetings:d.meetings.map(m=>m.id===id?{...m,minutes:makeExtractiveDraft(m.segments),status:'review'}:m)}));}),
  saveMinutes:(id:string,minutes:Minutes)=>run(async()=>{if(mode==='cloud'){const c=requireCloud();const row=unwrap(await c.client.from('meetings').update({minutes,status:'review'}).eq('id',id).select('*').single());setData(d=>({...d,meetings:d.meetings.map(m=>m.id===id?meetingFromRow(row):m)}));return;}setData(d=>({...d,meetings:d.meetings.map(m=>m.id===id?{...m,minutes,status:'review',version:m.version+1}:m)}));}),
  confirmMeeting:(id:string)=>run(async()=>{if(mode==='cloud'){const c=requireCloud(),current=data.meetings.find(m=>m.id===id);if(!current)throw new Error('미팅을 찾을 수 없습니다.');const row=unwrap(await c.client.rpc('confirm_meeting',{p_meeting_id:id,p_expected_version:current.version}));setData(d=>({...d,meetings:d.meetings.map(m=>m.id===id?meetingFromRow(row):m)}));return;}setData(d=>({...d,meetings:d.meetings.map(m=>m.id===id&&m.minutes?{...m,status:'confirmed'}:m)}));}),
  generateProposal:(meetingId:string,documentIds:string[])=>run(async()=>{const m=data.meetings.find(x=>x.id===meetingId);if(!m?.minutes)throw new Error('먼저 회의록을 생성해 주세요.');const docs=data.documents.filter(x=>documentIds.includes(x.id)&&x.allowAI);const content=`# ${m.title} 제안서 초안\n\n## 고객 요구 이해\n\n${m.minutes.requirements.map(x=>`- ${x.text}`).join('\n')||'- 회의록에서 확정된 요구사항을 추가해 주세요.'}\n\n## 제안 근거\n\n${docs.map(x=>`- ${x.name}: ${x.content.slice(0,160)}`).join('\n')||'- 선택된 내부 자료 없음'}\n\n## 확인이 필요한 사항\n\n${m.minutes.questions.map(x=>`- ${x}`).join('\n')}`;if(mode==='cloud'){const c=requireCloud();const row=unwrap(await c.client.from('proposals').insert({organization_id:c.organizationId,meeting_id:meetingId,title:`${m.title} 제안서`,content,status:'draft',source:'template',evidence_ids:m.minutes.requirements.flatMap(x=>x.sourceIds)}).select('*').single());const proposal=proposalFromRow(row);setData(d=>({...d,proposals:[proposal,...d.proposals]}));return proposal.id;}const proposalId=uid('prp');const p:Proposal={id:proposalId,meetingId,title:`${m.title} 제안서`,content,status:'draft',version:1,createdAt:new Date().toISOString(),source:'template',evidenceIds:m.minutes.requirements.flatMap(x=>x.sourceIds)};setData(d=>({...d,proposals:[p,...d.proposals]}));return proposalId;}),
  saveProposal:(id:string,content:string)=>run(async()=>{if(mode==='cloud'){const c=requireCloud();const row=unwrap(await c.client.from('proposals').update({content}).eq('id',id).select('*').single());setData(d=>({...d,proposals:d.proposals.map(p=>p.id===id?proposalFromRow(row):p)}));return;}setData(d=>({...d,proposals:d.proposals.map(p=>p.id===id?editProposal(p,content):p)}));}),
  approveProposal:(id:string)=>run(async()=>{if(mode==='cloud'){const c=requireCloud(),current=data.proposals.find(p=>p.id===id);if(!current)throw new Error('제안서를 찾을 수 없습니다.');const row=unwrap(await c.client.rpc('approve_proposal',{p_proposal_id:id,p_expected_version:current.version}));setData(d=>({...d,proposals:d.proposals.map(p=>p.id===id?proposalFromRow(row):p)}));return;}setData(d=>({...d,proposals:d.proposals.map(p=>p.id===id?{...p,status:'approved'}:p)}));}),
  addDocument:(file:File,category:string,allowAI:boolean)=>run(async()=>{if(!/\.(txt|md)$/i.test(file.name))throw new Error('참고 문서는 TXT 또는 MD만 등록할 수 있습니다.');const content=await file.text();if(mode==='cloud'){const c=requireCloud();const row=unwrap(await c.client.from('reference_documents').insert({organization_id:c.organizationId,name:file.name,category,content,allow_ai:allowAI}).select('*').single());setData(d=>({...d,documents:[documentFromRow(row),...d.documents]}));return;}const doc:ReferenceDocument={id:uid('doc'),name:file.name,category,content,allowAI,createdAt:new Date().toISOString()};setData(d=>({...d,documents:[doc,...d.documents]}));}),
  toggleDocument:(id:string)=>run(async()=>{const current=data.documents.find(x=>x.id===id);if(!current)return;if(mode==='cloud'){const c=requireCloud();const row=unwrap(await c.client.from('reference_documents').update({allow_ai:!current.allowAI}).eq('id',id).select('*').single());setData(d=>({...d,documents:d.documents.map(x=>x.id===id?documentFromRow(row):x)}));return;}setData(d=>({...d,documents:d.documents.map(x=>x.id===id?{...x,allowAI:!x.allowAI}:x)}));}),
  resetDemo:()=>{if(mode==='cloud')return;localStorage.removeItem(STORAGE_KEY);setData(SAMPLE_WORKSPACE);},
 };
}
