'use client';
import { useEffect,useRef,useState } from 'react';
import { Building2,CalendarDays,ChevronRight,FileAudio,FileText,FolderSearch,LayoutDashboard,Menu,Mic2,Plus,Search,Settings,ShieldCheck,Sparkles,Users,X,CheckCircle2,Clock3,Download,Database,CloudOff } from 'lucide-react';
import { formatTimestamp } from '@/lib/domain';
import type { Customer, Intake, Minutes, WorkspaceData, View } from '@/lib/types';

type Props=ReturnType<typeof import('@/lib/use-workspace').useWorkspace>;
const nav:{id:View;label:string;icon:any}[]=[{id:'dashboard',label:'대시보드',icon:LayoutDashboard},{id:'customers',label:'고객사',icon:Building2},{id:'meetings',label:'미팅',icon:Mic2},{id:'proposals',label:'제안서',icon:FileText},{id:'documents',label:'자료 저장소',icon:FolderSearch},{id:'settings',label:'설정',icon:Settings}];
const date=(v:string)=>new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const status=(v:string)=>({draft:'초안',review:'검토 필요',confirmed:'확정',approved:'승인'}[v]??v);

export function Workspace(w:Props){
 const [view,setView]=useState<View>('dashboard');const [mobile,setMobile]=useState(false);const [modal,setModal]=useState<'customer'|'meeting'|'document'|null>(null);const [selectedMeeting,setSelectedMeeting]=useState<string|null>(w.data.meetings[0]?.id??null);const [selectedProposal,setSelectedProposal]=useState<string|null>(w.data.proposals[0]?.id??null);const [query,setQuery]=useState('');
 const title=nav.find(n=>n.id===view)?.label;const go=(id:View)=>{setView(id);setMobile(false)};
 return <div className="app-shell">
  <aside className={`sidebar ${mobile?'open':''}`}><div className="brand"><span className="brand-mark">M</span><div><b>미팅노트</b><small>MEETING WORKSPACE</small></div><button className="icon close-mobile" onClick={()=>setMobile(false)} aria-label="메뉴 닫기"><X/></button></div>
   <div className="demo-card"><span>체험 모드</span><p>이 브라우저에만 저장됩니다.<br/>표시된 결과는 샘플 또는 규칙 기반입니다.</p></div>
   <nav>{nav.map(n=><button key={n.id} className={view===n.id?'active':''} onClick={()=>go(n.id)}><n.icon size={18}/>{n.label}</button>)}</nav>
   <div className="sidebar-foot">{w.connection.supabase?<Database size={17}/>:<CloudOff size={17}/>}<div><b>{w.connection.supabase?'Supabase 연결됨':'클라우드 미연결'}</b><small>{w.connection.supabase?'DB 준비 완료 · 현재 로컬 체험':w.connection.supabaseConfigured?'연결 확인 실패':'Supabase 설정 전'}</small></div></div>
  </aside>{mobile&&<button className="scrim" onClick={()=>setMobile(false)} aria-label="메뉴 닫기"/>}
  <main><header><button className="icon menu" onClick={()=>setMobile(true)} aria-label="메뉴 열기"><Menu/></button><div><small>고객 미팅 관리</small><h1>{title}</h1></div><div className="header-actions"><button className="quiet"><Search size={17}/>통합 검색</button><button className="avatar">BS</button></div></header>
   {w.error&&<div className="error-banner">{w.error}<button onClick={w.clearError}><X size={16}/></button></div>}
   <section className="content">
    {view==='dashboard'&&<Dashboard data={w.data} onGo={go} onOpen={()=>setModal('meeting')}/>} 
    {view==='customers'&&<Customers data={w.data} query={query} setQuery={setQuery} onOpen={()=>setModal('customer')} onMeetings={()=>go('meetings')}/>} 
    {view==='meetings'&&<Meetings data={w.data} selected={selectedMeeting} onSelect={setSelectedMeeting} onOpen={()=>setModal('meeting')} onAnalyze={w.analyze} onSave={w.saveMinutes} onConfirm={w.confirmMeeting} busy={w.busy}/>} 
    {view==='proposals'&&<Proposals data={w.data} selected={selectedProposal} onSelect={setSelectedProposal} onGenerate={w.generateProposal} onSave={w.saveProposal} onApprove={w.approveProposal}/>} 
    {view==='documents'&&<Documents data={w.data} onOpen={()=>setModal('document')} onToggle={w.toggleDocument}/>} 
    {view==='settings'&&<SettingsView connection={w.connection} onReset={w.resetDemo}/>} 
   </section>
  </main>
  {modal==='customer'&&<CustomerModal onClose={()=>setModal(null)} onSave={async x=>{await w.addCustomer(x);setModal(null)}}/>}
  {modal==='meeting'&&<MeetingModal customers={w.data.customers} onClose={()=>setModal(null)} onSave={async x=>{const id=await w.createMeeting(x);setSelectedMeeting(id);setModal(null);setView('meetings')}}/>}
  {modal==='document'&&<DocumentModal onClose={()=>setModal(null)} onSave={async(f,c,a)=>{await w.addDocument(f,c,a);setModal(null)}}/>}
  {w.busy&&<div className="busy"><span/>처리 중…</div>}
 </div>
}

function Dashboard({data,onGo,onOpen}:{data:WorkspaceData;onGo:(v:View)=>void;onOpen:()=>void}){const pending=data.meetings.filter(m=>m.status!=='confirmed').length;return <><div className="hero"><div><span className="eyebrow">TODAY’S WORKSPACE</span><h2>대화는 기록하고,<br/><em>제안은 앞으로.</em></h2><p>클로바노트 기록부터 고객 제안서까지 한 흐름으로 관리하세요.</p><div><button className="primary" onClick={onOpen}><Plus size={18}/>새 미팅 등록</button><button className="secondary" onClick={()=>onGo('proposals')}>제안서 보기<ChevronRight size={17}/></button></div></div><div className="hero-orbit"><Mic2/><span>REC</span></div></div>
<div className="stats"><Stat label="관리 고객사" value={data.customers.length} note="현재 워크스페이스"/><Stat label="검토할 미팅" value={pending} note="회의록 확인 필요"/><Stat label="작성 중 제안서" value={data.proposals.filter(p=>p.status==='draft').length} note="승인 전 초안"/><Stat label="사용 가능 자료" value={data.documents.filter(d=>d.allowAI).length} note="AI 전달 허용"/></div>
<div className="grid two"><Card title="최근 미팅" action="전체 보기" onAction={()=>onGo('meetings')}>{data.meetings.slice(0,4).map(m=><div className="row-item" key={m.id}><span className="date-block">{new Date(m.heldAt).getDate()}<small>{new Date(m.heldAt).toLocaleString('ko-KR',{month:'short'})}</small></span><div><b>{m.title}</b><small>{data.customers.find(c=>c.id===m.customerId)?.name} · {m.participants||'참석자 미입력'}</small></div><Badge value={m.status}/></div>)}</Card>
<Card title="작업 흐름"><div className="flow"><Flow n="01" icon={FileAudio} label="녹음 + TXT"/><i/><Flow n="02" icon={Sparkles} label="회의록 검토"/><i/><Flow n="03" icon={FileText} label="제안서 승인"/></div><div className="notice"><ShieldCheck/><div><b>외부 전송 범위 확인</b><p>TXT 경로에서는 녹음 파일을 GPT로 보내지 않습니다.</p></div></div></Card></div></>}
function Stat({label,value,note}:{label:string;value:number;note:string}){return <div className="stat"><span>{label}</span><strong>{String(value).padStart(2,'0')}</strong><small>{note}</small></div>}
function Card({title,action,onAction,children}:{title:string;action?:string;onAction?:()=>void;children:React.ReactNode}){return <div className="card"><div className="card-head"><h3>{title}</h3>{action&&<button onClick={onAction}>{action}<ChevronRight size={15}/></button>}</div>{children}</div>}
function Badge({value}:{value:string}){return <span className={`badge ${value}`}>{status(value)}</span>}
function Flow({n,icon:Icon,label}:{n:string;icon:any;label:string}){return <div><small>{n}</small><Icon/><b>{label}</b></div>}

function Customers({data,query,setQuery,onOpen,onMeetings}:{data:WorkspaceData;query:string;setQuery:(s:string)=>void;onOpen:()=>void;onMeetings:()=>void}){const list=data.customers.filter(c=>`${c.name}${c.industry}${c.contact}`.includes(query));return <><PageIntro title="고객사" text="고객별 미팅과 제안 과정을 한눈에 관리합니다." action="고객사 추가" onAction={onOpen}/><div className="toolbar"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="회사명, 담당자 검색"/></label><span>{list.length}개 고객사</span></div><div className="customer-grid">{list.map(c=><article key={c.id} className="customer-card"><div className="customer-logo">{c.name.slice(0,1)}</div><Badge value="active"/><h3>{c.name}</h3><p>{c.industry||'업종 미입력'}</p><dl><div><dt>담당자</dt><dd>{c.contact||'미지정'}</dd></div><div><dt>관련 미팅</dt><dd>{data.meetings.filter(m=>m.customerId===c.id).length}건</dd></div></dl><button onClick={onMeetings}>미팅 보기<ChevronRight size={16}/></button></article>)}</div>{!list.length&&<Empty text="등록된 고객사가 없습니다."/>}</>}
function PageIntro({title,text,action,onAction}:{title:string;text:string;action:string;onAction:()=>void}){return <div className="page-intro"><div><h2>{title}</h2><p>{text}</p></div><button className="primary" onClick={onAction}><Plus size={18}/>{action}</button></div>}

function Meetings({data,selected,onSelect,onOpen,onAnalyze,onSave,onConfirm,busy}:{data:WorkspaceData;selected:string|null;onSelect:(s:string)=>void;onOpen:()=>void;onAnalyze:(s:string)=>Promise<void>;onSave:(s:string,m:Minutes)=>Promise<void>;onConfirm:(s:string)=>Promise<void>;busy:boolean}){const m=data.meetings.find(x=>x.id===selected)??data.meetings[0];const audio=useRef<HTMLAudioElement>(null);return <><PageIntro title="미팅" text="원문 근거를 확인하며 회의록을 정리합니다." action="미팅 등록" onAction={onOpen}/><div className="split"><div className="list-panel">{data.meetings.map(x=><button key={x.id} className={m?.id===x.id?'selected':''} onClick={()=>onSelect(x.id)}><span className="list-icon"><Mic2/></span><div><b>{x.title}</b><small>{data.customers.find(c=>c.id===x.customerId)?.name} · {date(x.heldAt)}</small></div><Badge value={x.status}/></button>)}</div>{m?<div className="detail-panel"><div className="detail-head"><div><span className="eyebrow">{data.customers.find(c=>c.id===m.customerId)?.name}</span><h2>{m.title}</h2><p><CalendarDays size={15}/>{date(m.heldAt)} <Users size={15}/>{m.participants||'참석자 미입력'}</p></div><Badge value={m.status}/></div><div className="file-strip"><div><FileAudio/><span><b>{m.audioName||'녹음 없음'}</b><small>{m.audioName?'로컬 재생용 · GPT 미전송':'TXT 단독 입력'}</small></span></div><div><FileText/><span><b>{m.textName||'기록 없음'}</b><small>분석 입력</small></span></div></div>{m.audioUrl&&<audio ref={audio} controls src={m.audioUrl}/>}<div className="meeting-columns"><section><h3>음성 기록 <small>{m.segments.length}개 구간</small></h3><div className="transcript">{m.segments.map(s=><button key={s.id} onClick={()=>{if(audio.current&&s.startMs!==null){audio.current.currentTime=s.startMs/1000;audio.current.play()}}}><span>{formatTimestamp(s.startMs)}</span><div><b>{s.speaker??'화자 미지정'}</b><p>{s.text}</p><small>{s.id}</small></div></button>)}</div></section><section><div className="section-head"><h3>회의록</h3>{!m.minutes?<button className="primary small" disabled={busy} onClick={()=>onAnalyze(m.id)}><Sparkles size={15}/>초안 만들기</button>:<button className="primary small" onClick={()=>onConfirm(m.id)} disabled={m.status==='confirmed'}><CheckCircle2 size={15}/>{m.status==='confirmed'?'확정됨':'회의록 확정'}</button>}</div>{m.minutes?<MinutesEditor value={m.minutes} onSave={x=>onSave(m.id,x)}/>:<Empty text="TXT의 문장을 그대로 가져온 안전한 초안을 만들 수 있습니다. GPT 연결 전에는 결정 사항을 추정하지 않습니다."/>}</section></div></div>:<Empty text="미팅을 등록해 주세요."/>}</div></>}
function MinutesEditor({value,onSave}:{value:Minutes;onSave:(v:Minutes)=>Promise<void>}){const [draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value]);const field=(key:'summary'|'decisions'|'requirements')=><textarea value={draft[key].map(x=>x.text).join('\n')} onChange={e=>setDraft({...draft,[key]:e.target.value.split('\n').filter(Boolean).map((text,i)=>({text,sourceIds:draft[key][i]?.sourceIds??[]}))})}/>;return <div className="minutes"><span className="source-label">{value.source==='sample'?'샘플 결과':value.source==='gpt'?'GPT 생성':'규칙 기반 초안'}</span><label>핵심 요약{field('summary')}</label><label>결정 사항{field('decisions')}</label><label>요구사항{field('requirements')}</label><label>확인할 사항<textarea value={draft.questions.join('\n')} onChange={e=>setDraft({...draft,questions:e.target.value.split('\n').filter(Boolean)})}/></label><button className="secondary" onClick={()=>onSave(draft)}>수정 저장</button></div>}

function Proposals({data,selected,onSelect,onGenerate,onSave,onApprove}:{data:WorkspaceData;selected:string|null;onSelect:(s:string)=>void;onGenerate:(m:string,d:string[])=>Promise<string>;onSave:(id:string,c:string)=>Promise<void>;onApprove:(id:string)=>Promise<void>}){const p=data.proposals.find(x=>x.id===selected)??data.proposals[0];const [content,setContent]=useState(p?.content??'');useEffect(()=>setContent(p?.content??''),[p?.id,p?.content]);const ready=data.meetings.filter(m=>m.minutes);return <><div className="page-intro"><div><h2>제안서</h2><p>회의 근거와 허용된 참고 자료로 초안을 만듭니다.</p></div><select onChange={async e=>{if(!e.target.value)return;const id=await onGenerate(e.target.value,data.documents.filter(d=>d.allowAI).map(d=>d.id));onSelect(id);e.target.value='';}} defaultValue=""><option value="">회의록에서 초안 생성…</option>{ready.map(m=><option value={m.id} key={m.id}>{m.title}</option>)}</select></div><div className="split proposal"><div className="list-panel">{data.proposals.map(x=><button key={x.id} className={p?.id===x.id?'selected':''} onClick={()=>{onSelect(x.id);setContent(x.content)}}><span className="list-icon"><FileText/></span><div><b>{x.title}</b><small>버전 {x.version} · {x.source==='sample'?'샘플':'템플릿 초안'}</small></div><Badge value={x.status}/></button>)}</div>{p?<div className="detail-panel proposal-editor"><div className="detail-head"><div><span className="eyebrow">PROPOSAL · V{p.version}</span><h2>{p.title}</h2></div><Badge value={p.status}/></div><div className="warning"><Sparkles/><span><b>{p.source==='sample'?'샘플 문서입니다.':'연결 전 템플릿 초안입니다.'}</b> 고객 전달 전 근거와 문구를 검토하세요.</span></div><textarea className="document-editor" value={content} onChange={e=>setContent(e.target.value)}/><div className="editor-actions"><button className="secondary" onClick={()=>downloadText(`${p.title}.md`,content)}><Download size={16}/>Markdown</button><button className="secondary" onClick={()=>onSave(p.id,content)}>변경 저장</button><button className="primary" disabled={p.status==='approved'} onClick={()=>onApprove(p.id)}><ShieldCheck size={16}/>{p.status==='approved'?'승인됨':'최종 승인'}</button></div></div>:<Empty text="회의록에서 제안서 초안을 생성해 주세요."/>}</div></>}
function downloadText(name:string,text:string){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
function Documents({data,onOpen,onToggle}:{data:WorkspaceData;onOpen:()=>void;onToggle:(id:string)=>Promise<void>}){return <><PageIntro title="자료 저장소" text="첫 버전은 TXT·MD 자료를 직접 등록합니다. 자동 폴더 연결은 아직 구현되지 않았습니다." action="자료 등록" onAction={onOpen}/><div className="doc-table"><div className="table-head"><span>문서</span><span>분류</span><span>등록일</span><span>GPT 전달</span></div>{data.documents.map(d=><div key={d.id}><span><FileText/><b>{d.name}</b></span><span>{d.category}</span><span>{date(d.createdAt)}</span><span><button className={`toggle ${d.allowAI?'on':''}`} onClick={()=>onToggle(d.id)} aria-label="GPT 전달 허용 전환"><i/></button>{d.allowAI?'허용':'차단'}</span></div>)}</div></>}
function SettingsView({connection,onReset}:{connection:Props['connection'];onReset:()=>void}){return <><div className="page-intro"><div><h2>설정</h2><p>외부 서비스 연결 상태와 체험 데이터를 관리합니다.</p></div></div><div className="settings-grid"><Card title="서비스 연결"><Connection icon={Database} name="Supabase" text={connection.supabase?'프로젝트 API 응답을 확인했습니다. 로그인·클라우드 저장은 다음 단계에서 활성화합니다.':connection.supabaseConfigured?'환경 변수는 있지만 프로젝트 API에 연결하지 못했습니다.':'프로젝트 환경 변수를 등록하세요.'} connected={connection.supabase}/><Connection icon={Sparkles} name="OpenAI API" text={connection.openai?'서버 전용 키가 등록되었습니다.':'서버 전용 키가 필요합니다.'} connected={connection.openai}/><Connection icon={CloudOff} name="Vercel" text="배포 환경에서 실행 중입니다." connected={typeof window!=='undefined'&&window.location.hostname!=='127.0.0.1'&&window.location.hostname!=='localhost'}/></Card><Card title="체험 데이터"><p className="muted">이 브라우저에 저장된 고객사·미팅·제안서를 초기 샘플로 되돌립니다.</p><button className="danger" onClick={()=>confirm('체험 데이터를 초기화할까요?')&&onReset()}>체험 데이터 초기화</button></Card></div></>}
function Connection({icon:Icon,name,text,connected}:{icon:any;name:string;text:string;connected:boolean}){return <div className="connection"><span><Icon/></span><div><b>{name}</b><p>{text}</p></div><span className={`badge ${connected?'confirmed':'draft'}`}>{connected?'연결됨':'미연결'}</span></div>}
function Empty({text}:{text:string}){return <div className="empty"><FolderSearch/><p>{text}</p></div>}

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-bg" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="icon" onClick={onClose} aria-label="닫기"><X/></button></div>{children}</div></div>}
function CustomerModal({onClose,onSave}:{onClose:()=>void;onSave:(v:Omit<Customer,'id'|'createdAt'>)=>Promise<void>}){return <Modal title="고객사 추가" onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({name:String(f.get('name')),industry:String(f.get('industry')),contact:String(f.get('contact')),note:String(f.get('note'))})}}><Field label="회사명" name="name" required/><Field label="업종" name="industry"/><Field label="담당자" name="contact"/><label>메모<textarea name="note"/></label><button className="primary wide">고객사 저장</button></form></Modal>}
function MeetingModal({customers,onClose,onSave}:{customers:Customer[];onClose:()=>void;onSave:(v:Intake)=>Promise<void>}){const [audio,setAudio]=useState<File|null>(null),[text,setText]=useState<File|null>(null);return <Modal title="클로바노트 미팅 등록" onClose={onClose}><div className="modal-note"><ShieldCheck/>TXT가 있으면 녹음은 GPT로 전송하지 않습니다. 현재 버전은 TXT 기반 분석만 지원합니다.</div><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({customerId:String(f.get('customer')),title:String(f.get('title')),heldAt:String(f.get('heldAt')),participants:String(f.get('participants')),audio,text})}}><label>고객사<select name="customer" required><option value="">선택하세요</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><Field label="미팅 제목" name="title" required/><Field label="미팅 일시" name="heldAt" type="datetime-local" required/><Field label="참석자" name="participants"/><div className="upload-pair"><FileBox title="녹음 파일" hint="M4A · MP3 · WAV · AAC · AMR" file={audio} accept=".m4a,.mp3,.wav,.aac,.amr" onFile={setAudio}/><FileBox title="음성 기록 TXT" hint="클로바노트에서 내려받은 TXT" file={text} accept=".txt" onFile={setText}/></div><button className="primary wide" disabled={!text}>파일 확인 후 등록</button></form></Modal>}
function DocumentModal({onClose,onSave}:{onClose:()=>void;onSave:(f:File,c:string,a:boolean)=>Promise<void>}){const [file,setFile]=useState<File|null>(null);return <Modal title="참고 자료 등록" onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(!file)return;const f=new FormData(e.currentTarget);onSave(file,String(f.get('category')),f.get('allow')==='on')}}><FileBox title="TXT 또는 MD" hint="원본 전체가 아닌 필요한 자료만 등록하세요." file={file} accept=".txt,.md" onFile={setFile}/><Field label="분류" name="category" required/><label className="check"><input type="checkbox" name="allow"/>제안서 생성을 위해 GPT로 발췌 전송 허용</label><button className="primary wide" disabled={!file}>자료 등록</button></form></Modal>}
function Field({label,name,type='text',required=false}:{label:string;name:string;type?:string;required?:boolean}){return <label>{label}<input name={name} type={type} required={required}/></label>}
function FileBox({title,hint,file,accept,onFile}:{title:string;hint:string;file:File|null;accept:string;onFile:(f:File|null)=>void}){return <label className={`file-box ${file?'has':''}`}><input type="file" accept={accept} onChange={e=>onFile(e.target.files?.[0]??null)}/>{file?<CheckCircle2/>:<Plus/>}<b>{file?.name??title}</b><small>{file?`${(file.size/1024/1024).toFixed(1)} MB`:hint}</small></label>}
